### ISSUE TITLE
VirtualBox multinode setup failed due to /usr/local/var/mesos/deploy does not exist

### ISSUE THREAD

**Issue by runningman84** [everpeace/vagrant-mesos#54]
```
    master1: The Berkshelf shelf is at "/home/phil/.berkshelf/vagrant-berkshelf/shelves/berkshelf20150424-17054-1ncpzp6-master1"
==> master1: Sharing cookbooks with VM
==> master1: Importing base box 'everpeace/mesos'...
==> master1: Matching MAC address for NAT networking...
==> master1: Checking if box 'everpeace/mesos' is up to date...
==> master1: A newer version of the box 'everpeace/mesos' is available! You currently
==> master1: have version '0.20.1.2'. The latest is version '0.21.0.0'. Run
==> master1: `vagrant box update` to update.
==> master1: Setting the name of the VM: vagrant-mesos-master1
==> master1: Updating Vagrant's Berkshelf...
==> master1: Resolving cookbook dependencies...
==> master1: Using 7-zip (1.0.2)
==> master1: Using ark (0.9.0)
==> master1: Using apt (2.7.0)
==> master1: Using aufs (0.1.1)
==> master1: Using build-essential (2.2.3)
==> master1: Using chef_handler (1.1.6)
==> master1: Using device-mapper (0.1.0)
==> master1: Using dmg (2.2.2)
==> master1: Using docker (0.37.0) from git://github.com/bflad/chef-docker.git (at master)
==> master1: Using dpkg_autostart (0.1.12)
==> master1: Using git (4.2.2)
==> master1: Using golang (1.5.0)
==> master1: Using homebrew (1.12.0)
==> master1: Using iptables (1.0.0)
==> master1: Using iptables-ng (2.2.6)
==> master1: Using java (1.31.0)
==> master1: Using lxc (2.0.0)
==> master1: Using maven (1.3.0)
==> master1: Using mesos (0.2.2) from git://github.com/everpeace/cookbook-mesos.git (at master)
==> master1: Using modules (0.2.0)
==> master1: Using ohai (2.0.1)
==> master1: Using packagecloud (0.0.17)
==> master1: Using python (1.4.6)
==> master1: Using polipo (0.1.0)
==> master1: Using runit (1.6.0)
==> master1: Using sysctl (0.6.2)
==> master1: Using ulimit (0.3.3)
==> master1: Using windows (1.36.6)
==> master1: Using yum (3.6.0)
==> master1: Using yum-epel (0.6.0)
==> master1: Vendoring 7-zip (1.0.2) to /home/phil/.berkshelf/vagrant-berkshelf/shelves/berkshelf20150424-17054-1ncpzp6-master1/7-zip
==> master1: Vendoring apt (2.7.0) to /home/phil/.berkshelf/vagrant-berkshelf/shelves/berkshelf20150424-17054-1ncpzp6-master1/apt
==> master1: Vendoring ark (0.9.0) to /home/phil/.berkshelf/vagrant-berkshelf/shelves/berkshelf20150424-17054-1ncpzp6-master1/ark
==> master1: Vendoring aufs (0.1.1) to /home/phil/.berkshelf/vagrant-berkshelf/shelves/berkshelf20150424-17054-1ncpzp6-master1/aufs
==> master1: Vendoring build-essential (2.2.3) to /home/phil/.berkshelf/vagrant-berkshelf/shelves/berkshelf20150424-17054-1ncpzp6-master1/build-essential
==> master1: Vendoring chef_handler (1.1.6) to /home/phil/.berkshelf/vagrant-berkshelf/shelves/berkshelf20150424-17054-1ncpzp6-master1/chef_handler
==> master1: Vendoring device-mapper (0.1.0) to /home/phil/.berkshelf/vagrant-berkshelf/shelves/berkshelf20150424-17054-1ncpzp6-master1/device-mapper
==> master1: Vendoring dmg (2.2.2) to /home/phil/.berkshelf/vagrant-berkshelf/shelves/berkshelf20150424-17054-1ncpzp6-master1/dmg
==> master1: Vendoring docker (0.37.0) to /home/phil/.berkshelf/vagrant-berkshelf/shelves/berkshelf20150424-17054-1ncpzp6-master1/docker
==> master1: Vendoring dpkg_autostart (0.1.12) to /home/phil/.berkshelf/vagrant-berkshelf/shelves/berkshelf20150424-17054-1ncpzp6-master1/dpkg_autostart
==> master1: Vendoring git (4.2.2) to /home/phil/.berkshelf/vagrant-berkshelf/shelves/berkshelf20150424-17054-1ncpzp6-master1/git
==> master1: Vendoring golang (1.5.0) to /home/phil/.berkshelf/vagrant-berkshelf/shelves/berkshelf20150424-17054-1ncpzp6-master1/golang
==> master1: Vendoring homebrew (1.12.0) to /home/phil/.berkshelf/vagrant-berkshelf/shelves/berkshelf20150424-17054-1ncpzp6-master1/homebrew
==> master1: Vendoring iptables (1.0.0) to /home/phil/.berkshelf/vagrant-berkshelf/shelves/berkshelf20150424-17054-1ncpzp6-master1/iptables
==> master1: Vendoring iptables-ng (2.2.6) to /home/phil/.berkshelf/vagrant-berkshelf/shelves/berkshelf20150424-17054-1ncpzp6-master1/iptables-ng
==> master1: Vendoring java (1.31.0) to /home/phil/.berkshelf/vagrant-berkshelf/shelves/berkshelf20150424-17054-1ncpzp6-master1/java
==> master1: Vendoring lxc (2.0.0) to /home/phil/.berkshelf/vagrant-berkshelf/shelves/berkshelf20150424-17054-1ncpzp6-master1/lxc
==> master1: Vendoring maven (1.3.0) to /home/phil/.berkshelf/vagrant-berkshelf/shelves/berkshelf20150424-17054-1ncpzp6-master1/maven
==> master1: Vendoring mesos (0.2.2) to /home/phil/.berkshelf/vagrant-berkshelf/shelves/berkshelf20150424-17054-1ncpzp6-master1/mesos
==> master1: Vendoring modules (0.2.0) to /home/phil/.berkshelf/vagrant-berkshelf/shelves/berkshelf20150424-17054-1ncpzp6-master1/modules
==> master1: Vendoring ohai (2.0.1) to /home/phil/.berkshelf/vagrant-berkshelf/shelves/berkshelf20150424-17054-1ncpzp6-master1/ohai
==> master1: Vendoring packagecloud (0.0.17) to /home/phil/.berkshelf/vagrant-berkshelf/shelves/berkshelf20150424-17054-1ncpzp6-master1/packagecloud
==> master1: Vendoring polipo (0.1.0) to /home/phil/.berkshelf/vagrant-berkshelf/shelves/berkshelf20150424-17054-1ncpzp6-master1/polipo
==> master1: Vendoring python (1.4.6) to /home/phil/.berkshelf/vagrant-berkshelf/shelves/berkshelf20150424-17054-1ncpzp6-master1/python
==> master1: Vendoring runit (1.6.0) to /home/phil/.berkshelf/vagrant-berkshelf/shelves/berkshelf20150424-17054-1ncpzp6-master1/runit
==> master1: Vendoring sysctl (0.6.2) to /home/phil/.berkshelf/vagrant-berkshelf/shelves/berkshelf20150424-17054-1ncpzp6-master1/sysctl
==> master1: Vendoring ulimit (0.3.3) to /home/phil/.berkshelf/vagrant-berkshelf/shelves/berkshelf20150424-17054-1ncpzp6-master1/ulimit
==> master1: Vendoring windows (1.36.6) to /home/phil/.berkshelf/vagrant-berkshelf/shelves/berkshelf20150424-17054-1ncpzp6-master1/windows
==> master1: Vendoring yum (3.6.0) to /home/phil/.berkshelf/vagrant-berkshelf/shelves/berkshelf20150424-17054-1ncpzp6-master1/yum
==> master1: Vendoring yum-epel (0.6.0) to /home/phil/.berkshelf/vagrant-berkshelf/shelves/berkshelf20150424-17054-1ncpzp6-master1/yum-epel
==> master1: Fixed port collision for 22 => 2222. Now on port 2200.
==> master1: Clearing any previously set network interfaces...
==> master1: Preparing network interfaces based on configuration...
    master1: Adapter 1: nat
    master1: Adapter 2: hostonly
==> master1: Forwarding ports...
    master1: 22 => 2200 (adapter 1)
==> master1: Running 'pre-boot' VM customizations...
==> master1: Booting VM...
==> master1: Waiting for machine to boot. This may take a few minutes...
    master1: SSH address: 127.0.0.1:2200
    master1: SSH username: vagrant
    master1: SSH auth method: private key
    master1: Warning: Remote connection disconnect. Retrying...
==> master1: Machine booted and ready!
==> master1: Checking for guest additions in VM...
==> master1: Setting hostname...
==> master1: Configuring and enabling network interfaces...
==> master1: Mounting shared folders...
    master1: /vagrant => /home/phil/dev/vagrant-mesos/multinodes
    master1: /tmp/vagrant-chef-6/chef-solo-1/cookbooks => /home/phil/.berkshelf/vagrant-berkshelf/shelves/berkshelf20150424-17054-1ncpzp6-master1
==> master1: Installing Chef 12.2.1 Omnibus package...
==> master1: Downloading Chef 12.2.1 for ubuntu...
==> master1: downloading https://www.chef.io/chef/metadata?v=12.2.1&prerelease=false&nightlies=false&p=ubuntu&pv=14.04&m=x86_64
==> master1:   to file /tmp/install.sh.1760/metadata.txt
==> master1: trying wget...
==> master1: url        https://opscode-omnibus-packages.s3.amazonaws.com/ubuntu/13.04/x86_64/chef_12.2.1-1_amd64.deb
==> master1: md5        84119f54115d754373c9891b8759497c
==> master1: sha256     8e0a8a2477c11615f86ffe686a68fa6636112ba82ebe6bb22daa5dd416f3c13e
==> master1: downloaded metadata file looks valid...
==> master1: downloading https://opscode-omnibus-packages.s3.amazonaws.com/ubuntu/13.04/x86_64/chef_12.2.1-1_amd64.deb
==> master1:   to file /tmp/vagrant-cache/vagrant_omnibus/chef_12.2.1-1_amd64.deb
==> master1: trying wget...
==> master1: Comparing checksum with sha256sum...
==> master1: Installing Chef 12.2.1
==> master1: installing with dpkg...
==> master1: (Reading database ... 76621 files and directories currently installed.)
==> master1: Preparing to unpack .../chef_12.2.1-1_amd64.deb ...
==> master1: Unpacking chef (12.2.1-1) over (11.16.2-1) ...
==> master1: dpkg: warning: unable to delete old directory '/opt/chef/embedded/lib/ruby/gems/1.9.1/specifications': Directory not empty
==> master1: dpkg: warning: unable to delete old directory '/opt/chef/embedded/lib/ruby/gems/1.9.1/cache': Directory not empty
==> master1: dpkg: warning: unable to delete old directory '/opt/chef/embedded/lib/ruby/gems/1.9.1/gems': Directory not empty
==> master1: dpkg: warning: unable to delete old directory '/opt/chef/embedded/lib/ruby/gems/1.9.1': Directory not empty
==> master1: Setting up chef (12.2.1-1) ...
==> master1: Thank you for installing Chef!
==> master1: Running provisioner: shell...
    master1: Running: inline script
==> master1: stdin: is not a tty
==> master1: Running provisioner: chef_solo...
Generating chef JSON and uploading...
==> master1: Running chef-solo...
==> master1: stdin: is not a tty
==> master1: [2015-04-24T07:55:10+00:00] INFO: Forking chef instance to converge...
==> master1: [2015-04-24T07:55:11+00:00] INFO: *** Chef 12.2.1 ***
==> master1: [2015-04-24T07:55:11+00:00] INFO: Chef-client pid: 1940
==> master1: [2015-04-24T07:55:17+00:00] INFO: Setting the run_list to ["recipe[apt]", "recipe[mesos::master]"] from CLI options
==> master1: [2015-04-24T07:55:17+00:00] INFO: Run List is [recipe[apt], recipe[mesos::master]]
==> master1: [2015-04-24T07:55:17+00:00] INFO: Run List expands to [apt, mesos::master]
==> master1: [2015-04-24T07:55:17+00:00] INFO: Starting Chef Run for master1
==> master1: [2015-04-24T07:55:17+00:00] INFO: Running start handlers
==> master1: [2015-04-24T07:55:17+00:00] INFO: Start handlers complete.
==> master1: [2015-04-24T07:55:18+00:00] INFO: node[:mesos][:prefix] is ignored. prefix will be set with /usr/local .
==> master1: [2015-04-24T07:55:18+00:00] WARN: Cloning resource attributes for template[/etc/init/mesos-master.conf] from prior resource (CHEF-3694)
==> master1: [2015-04-24T07:55:18+00:00] WARN: Previous template[/etc/init/mesos-master.conf]: /tmp/vagrant-chef-6/chef-solo-1/cookbooks/mesos/libraries/helpers.rb:177:in `deploy_service_scripts'
==> master1: [2015-04-24T07:55:18+00:00] WARN: Current  template[/etc/init/mesos-master.conf]: /tmp/vagrant-chef-6/chef-solo-1/cookbooks/mesos/libraries/helpers.rb:200:in `activate_master_service_scripts'
==> master1: [2015-04-24T07:55:42+00:00] INFO: execute[apt-get-update-periodic] ran successfully
==> master1: [2015-04-24T07:55:42+00:00] INFO: execute[apt-get-update-periodic] sending touch action to file[/var/lib/apt/periodic/update-success-stamp] (immediate)
==> master1: [2015-04-24T07:55:42+00:00] INFO: file[/var/lib/apt/periodic/update-success-stamp] updated atime and mtime to 2015-04-24 07:55:42 +0000
==> master1: [2015-04-24T07:55:42+00:00] INFO: directory[/usr/local/var/mesos/deploy] mode changed to 644
==> master1: [2015-04-24T07:55:47+00:00] INFO: bash[add an apt's trusted key for mesosphere] ran successfully
==> master1: [2015-04-24T07:56:05+00:00] INFO: bash[add mesosphere repository] ran successfully
==> master1: [2015-04-24T07:56:44+00:00] INFO: apt_package[mesos] installed mesos at 0.21.0-1.0.ubuntu1404
==> master1: 
==> master1: ================================================================================
==> master1: Error executing action `create` on resource 'template[/usr/local/var/mesos/deploy/masters]'
==> master1: ================================================================================
==> master1: 
==> master1: 
==> master1: Chef::Exceptions::EnclosingDirectoryDoesNotExist
==> master1: ------------------------------------------------
==> master1: Parent directory /usr/local/var/mesos/deploy does not exist.
==> master1: 
==> master1: 
==> master1: Resource Declaration:
==> master1: ---------------------
==> master1: # In /tmp/vagrant-chef-6/chef-solo-1/cookbooks/mesos/recipes/master.rb
==> master1: 
==> master1: 
==> master1: 
==> master1:  47: template File.join(deploy_dir, "masters") do
==> master1: 
==> master1:  48:   source "masters.erb"
==> master1: 
==> master1:  49:   mode 0644
==> master1: 
==> master1:  50:   owner "root"
==> master1: 
==> master1:  51:   group "root"
==> master1: 
==> master1:  52: end
==> master1: 
==> master1:  53: 
==> master1: 
==> master1: 
==> master1: Compiled Resource:
==> master1: ------------------
==> master1: # Declared in /tmp/vagrant-chef-6/chef-solo-1/cookbooks/mesos/recipes/master.rb:47:in `from_file'
==> master1: 
==> master1: template("/usr/local/var/mesos/deploy/masters") do
==> master1:   action "create"
==> master1:   retries 0
==> master1:   retry_delay 2
==> master1:   default_guard_interpreter :default
==> master1:   path "/usr/local/var/mesos/deploy/masters"
==> master1:   backup 5
==> master1:   atomic_update true
==> master1:   source "masters.erb"
==> master1:   declared_type :template
==> master1:   cookbook_name :mesos
==> master1:   recipe_name "master"
==> master1:   mode 420
==> master1:   owner "root"
==> master1:   group "root"
==> master1: end
==> master1: 
==> master1: 
==> master1: [2015-04-24T07:56:44+00:00] INFO: Running queued delayed notifications before re-raising exception
==> master1: [2015-04-24T07:56:44+00:00] ERROR: Running exception handlers
==> master1: [2015-04-24T07:56:44+00:00] ERROR: Exception handlers complete
==> master1: [2015-04-24T07:56:44+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> master1: [2015-04-24T07:56:44+00:00] ERROR: template[/usr/local/var/mesos/deploy/masters] (mesos::master line 47) had an error: Chef::Exceptions::EnclosingDirectoryDoesNotExist: Parent directory /usr/local/var/mesos/deploy does not exist.
==> master1: [2015-04-24T07:56:44+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.
```

**Comment by everpeace** [comment]
In the latest `cookbook-mesos`, `master` recipe does create deploy directory before putting config files. see [here](https://github.com/everpeace/cookbook-mesos/blob/master/recipes/master.rb#L16-L24).

I suspect that your cached cookbook might be old one.

**Comment by everpeace** [comment]
Or, please try to update  `vagrant-mesos` vm image like below:

```bash
$ vagrant box update everpeace/mesos
$ vagrant up
```

or remove and up again (please refer to `vagrant box help` for manipulating vagrant boxes in your local).

**Comment by everpeace** [comment]
@runningman84  Do you still have this problem??  Would you mind closing this issue?

**Comment by everpeace** [comment]
if you had the issue, please feel free to re-open it.
